### PR TITLE
New Italian pool and node

### PR DESCRIPTION
**Pull request by angelobpool**
New Italian pool and node https://coinpoolit.webhop.me/trtl

### CODE REVIEW

**Comment by SoreGums** [comment]
how does someone use your node as remote-daemon? i don't see any information on the link provided

**Comment by zpalmtree** [comment]
Just `--remote-daemon coinpoolit.webhop.me` works fine..
I'm not sure how valuable remote nodes being on this page is - is it not just needlessly duplicating the json information?

Why not make the website consume the JSON and display them on this page instead?
Or... are nodes on this website needed? We already have pages which list them, for example:
http://trtl.nodes.pub/
and
http://trtl.rocks/nodes

which don't get outdated because the use the JSON.

**Comment by SoreGums** [comment]
make a great point there z.

how about we just remove nodes and include the three links to the json repo and the 2x node sites

**Comment by SoreGums** [comment]
due to the removal of nodes list #97, not going to merge this

please add your node to the json list over at https://github.com/turtlecoin/turtlecoin-nodes-json

feel free to edit your file to only add the pool

**Comment by SoreGums** [comment]
nevermind - edited easily enough here - all done

**Pull request merged**
