### PR TITLE
Adding HA Turtle Node to nodes list

### PR DESCRIPTION
**Pull request by NightOwlCoder**
please add my public node to the list.

### CODE REVIEW

**Comment by SoreGums** [comment]
is there supposed to be a website at http://turtle.hapool.pw/ ?

doesn't seem to be one.

note the other links open up websites, some show block explorer some show daemon node status - some don't work and should probably be removed.

**Comment by SoreGums** [comment]
due to the removal of nodes list #97, not going to merge this

please add your node to the json list over at https://github.com/turtlecoin/turtlecoin-nodes-json

**Comment by NightOwlCoder** [comment]
Hey @SoreGums , I saw in your #97:
> direct people to the json list and the two tracking sites

I go the node lists, but what are the 2 tracking sites?

**Comment by SoreGums** [comment]
under nodes on the site https://turtlecoin.github.io/turtleturtle.org/ (also in #97)

there are 2x sites that list the public nodes that are in the json file.

image

[trtl.nodes.pub](http://trtl.nodes.pub/) → Public TurtleCoin nodes listing with availability tracking and node fee support  
[trtl.rocks](http://trtl.rocks/nodes) → Live public TurtleCoin nodes tracker/reporter

**Pull request closed without merging**
